pages = ["index.md",
    "getting_started.md",
    "Tutorials" => [
        "tutorials/minibatch.md",
        "tutorials/symbolic.md",
        "tutorials/constraints.md",
    ],
    "Examples" => [
        "examples/rosenbrock.md",
    ],
    "Basics" => [
        "API/optimization_problem.md",
        "API/optimization_function.md",
        "API/solve.md",
        "API/optimization_solution.md",
        "API/modelingtoolkit.md",
        "API/FAQ.md",
    ],
    "Optimizer Packages" => [
        "BlackBoxOptim.jl" => "optimization_packages/blackboxoptim.md",
        "CMAEvolutionStrategy.jl" => "optimization_packages/cmaevolutionstrategy.md",
        "Evolutionary.jl" => "optimization_packages/evolutionary.md",
        "Flux.jl" => "optimization_packages/flux.md",
        "GCMAES.jl" => "optimization_packages/gcmaes.md",
        "MathOptInterface.jl" => "optimization_packages/mathoptinterface.md",
        "Metaheuristics.jl" => "optimization_packages/metaheuristics.md",
        "MultistartOptimization.jl" => "optimization_packages/multistartoptimization.md",
        "NLopt.jl" => "optimization_packages/nlopt.md",
        "NOMAD.jl" => "optimization_packages/nomad.md",
        # "Nonconvex.jl" => "optimization_packages/nonconvex.md",
        "Optim.jl" => "optimization_packages/optim.md",
        "Optimisers.jl" => "optimization_packages/optimisers.md",
        "QuadDIRECT.jl" => "optimization_packages/quaddirect.md",
        "SpeedMapping.jl" => "optimization_packages/speedmapping.md",
    ],
]
