name: Documentation
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  build-and-deploy-docs:
    name: "Documentation"
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
