name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: DiffEqFlux.jl, group: All, subdirs: ".,lib/OptimizationOptimJL,lib/OptimizationOptimisers"}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE1, subdirs: ".,lib/OptimizationOptimJL,lib/OptimizationOptimisers"}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE2, subdirs: ".,lib/OptimizationOptimJL,lib/OptimizationOptimisers"}
          - {user: SciML, repo: ModelingToolkit.jl, group: Optimization, subdirs: ".,lib/*"}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
      upstream-subdirs: "${{ matrix.package.subdirs }}"
      julia-version: "1"
    secrets: "inherit"
